---
title: "Basic usage of tekkamaki"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Basic usage of tekkamaki}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, setup-hidden}
#| include: false
knitr::opts_chunk$set(fig.alt = " ")
```

```{r, setup}
library(conflicted)
library(tekkamaki)
library(dplyr)
library(ggplot2)
palette_discrete = grDevices::palette.colors(palette = "Okabe-Ito")[-1]
theme_palette = ggplot2::theme(
  palette.colour.continuous = "viridis",
  palette.fill.continuous = "viridis",
  palette.colour.discrete = palette_discrete,
  palette.fill.discrete = palette_discrete
)
```

Run simulation:

```{r, simulation}
set.seed(42)
result = tekka("-y80 -l3") |> print()
```

A result is a nested tibble with two columns: `sample_family` and `demography`:

```{r, result}
sample_family = result$sample_family[[1L]] |> print()
demography = result$demography[[1L]] |> print()
```

Here is an example of visualizing demography:

```{r, demography}
df = demography |>
  dplyr::mutate(time = year + 0.25 * season) |>
  dplyr::mutate(age = ifelse(age >= 4, "adult", "juvenile")) |>
  dplyr::summarize(count = sum(count), .by = c(time, location, age)) |>
  tidyr::complete(time, location, age, fill = list(count = 0L))

ggplot(df) +
  aes(time, count) +
  geom_path(aes(colour = age, group = age)) +
  facet_grid(vars(location)) +
  theme_bw(base_size = 12) +
  theme_palette +
  theme(legend.position = "top")
```
