// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
void zzz_do_nothing();
extern "C" SEXP _tekkamaki_zzz_do_nothing() {
  BEGIN_CPP11
    zzz_do_nothing();
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_tekkamaki_zzz_do_nothing", (DL_FUNC) &_tekkamaki_zzz_do_nothing, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_tekkamaki(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
