// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// config.cpp
cpp11::strings tekka_path_config();
extern "C" SEXP _tekkamaki_tekka_path_config() {
  BEGIN_CPP11
    return cpp11::as_sexp(tekka_path_config());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_tekkamaki_tekka_path_config", (DL_FUNC) &_tekkamaki_tekka_path_config, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_tekkamaki(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
