// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_rnbinom
std::vector<int> cpp_rnbinom(int n, double size, double mu);
RcppExport SEXP _tekkamaki_cpp_rnbinom(SEXP nSEXP, SEXP sizeSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rnbinom(n, size, mu));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tekka
Rcpp::CharacterVector cpp_tekka(const std::vector<std::string>& args);
RcppExport SEXP _tekkamaki_cpp_tekka(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tekka(args));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tekkamaki_cpp_rnbinom", (DL_FUNC) &_tekkamaki_cpp_rnbinom, 3},
    {"_tekkamaki_cpp_tekka", (DL_FUNC) &_tekkamaki_cpp_tekka, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_tekkamaki(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
