# Generated by cpp11: do not edit by hand

migration_matrices <- function() {
  .Call(`_tekkamaki_migration_matrices`)
}

natural_mortality <- function() {
  .Call(`_tekkamaki_natural_mortality`)
}

fishing_mortality <- function() {
  .Call(`_tekkamaki_fishing_mortality`)
}

weight_for_age <- function() {
  .Call(`_tekkamaki_weight_for_age`)
}

read_json <- function(file) {
  invisible(.Call(`_tekkamaki_read_json`, file))
}

cpp_rnbinom <- function(n, size, mu) {
  .Call(`_tekkamaki_cpp_rnbinom`, n, size, mu)
}
