# Generated by cpp11: do not edit by hand

tekka_path_config <- function() {
  .Call(`_tekkamaki_tekka_path_config`)
}

default_parameters_json_text <- function() {
  .Call(`_tekkamaki_default_parameters_json_text`)
}
