# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @details
#' `cpp_blackthunnus` is a Rcpp function to call blackthunnus
#' @rdname blackthunnus
cpp_blackthunnus <- function(args) {
    .Call(`_tekkamaki_cpp_blackthunnus`, args)
}

