# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @details
#' `cpp_rnbinom` generates nbinom random numbers.
#' @rdname nbinom
#' @inheritParams stats::rnbinom
#' @seealso stats::rnbinom
cpp_rnbinom <- function(n, size, mu) {
    .Call(`_tekkamaki_cpp_rnbinom`, n, size, mu)
}

#' @details
#' `cpp_tekka` is a Rcpp function to call tekka
#' @rdname tekka
cpp_tekka <- function(args) {
    .Call(`_tekkamaki_cpp_tekka`, args)
}

